In [1]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha"],
    "Age": [22, None, 21, 23],
    "Marks": [65, 72, None, 90]
}
df = pd.DataFrame(data)

In [2]:
print(df)

     Name   Age  Marks
0     Ali  22.0   65.0
1    Sara   NaN   72.0
2   Ahmed  21.0    NaN
3  Ayesha  23.0   90.0

In [3]:
df.isnull()

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [4]:
df.isnull().sum()

Name     0
Age      1
Marks    1
dtype: int64

In [5]:
df.dropna()

     Name   Age  Marks
0     Ali  22.0   65.0
3  Ayesha  23.0   90.0

In [6]:
df["Age"].fillna(df["Age"].mean())

0    22.0
1    22.0
2    21.0
3    23.0
Name: Age, dtype: float64

In [7]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [8]:
df.dropna

<bound method DataFrame.dropna of      Name   Age  Marks
0     Ali  22.0   65.0
1    Sara  22.0   72.0
2   Ahmed  21.0    NaN
3  Ayesha  23.0   90.0>

In [16]:
data = {
    "Name": ["Ali", "Sara", "Ali", "Ahmed"],
    "Age": [22, 24, 22, 21],
    "Marks": [65, 72, 65, 80]
}

df = pd.DataFrame(data)

In [17]:
df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [18]:
df.duplicated().sum()

np.int64(1)

In [14]:
df.drop_duplicates()

     Name   Age  Marks
0     Ali  22.0   65.0
1    Sara  22.0   72.0
2   Ahmed  21.0    NaN
3  Ayesha  23.0   90.0

EDA

In [19]:
data = {
    "Name": ["Ali", "Sara", "Ali", "Ahmed"],
    "Age": [22, 24, 22, 21],
    "Marks": [65, 72, 65, 80]
}

df = pd.DataFrame(data)

In [21]:
df.shape

(4, 3)

In [22]:
df.info

<bound method DataFrame.info of     Name  Age  Marks
0    Ali   22     65
1   Sara   24     72
2    Ali   22     65
3  Ahmed   21     80>

In [24]:
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   22.250000  70.500000
std     1.258306   7.141428
min    21.000000  65.000000
25%    21.750000  65.000000
50%    22.000000  68.500000
75%    22.500000  74.000000
max    24.000000  80.000000

In [25]:
marks = [65, 68, 70, 72, 150]

In [26]:
Q1 = df["Marks"].quantile(0.25)
Q3 = df["Marks"].quantile(0.75)

IQR = Q3 - Q1

print(IQR)

9.0

In [27]:
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print(lower)
print(upper)

51.5
87.5

In [30]:
df.loc[4] = ["Zain", 22, 150]

In [31]:
df[(df["Marks"] < lower) | (df["Marks"] > upper)]

   Name  Age  Marks
4  Zain   22    150

In [32]:
Q1 = df["Marks"].quantile(0.25)
Q3 = df["Marks"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df[(df["Marks"] < lower) | (df["Marks"] > upper)]

   Name  Age  Marks
4  Zain   22    150

In [33]:
df

    Name  Age  Marks
0    Ali   22     65
1   Sara   24     72
2    Ali   22     65
3  Ahmed   21     80
4   Zain   22    150

In [34]:
Q1 = df["Marks"].quantile(0.25)
Q3 = df["Marks"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print(Q1)
print(Q3)
print(IQR)
print(lower)
print(upper)

65.0
80.0
15.0
42.5
102.5